[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/invariant","programs/locker", "programs/staker", "programs/invariant_autoswap"]
# members = ["programs/invariant"]

[programs.localnet]
invariant = "iNvTyprs4TX8m6UeUEkeqDFjAL9zRCRWcexK9Sd4WEU"
locker = "LockDkUjGpMHewP4cbP7XRpiiC4ciQaPALbwUALCEJp"
staker = "MJ6WF1tpEJ7Gk8ULqejDJapRfqBwBEp1dH5QvAgYxu9"
invariant_autoswap = "AuTonVN41Ne17RGR2o9qTj3TmtKcTwmUUy1ebbTmpiU"

[programs.testnet]
invariant = "8HJq6TfDVvZQJWu2RzjvV9W1yNkJNCng2iYQWCxkp7bL"

[programs.devnet]
invariant = "8HJq6TfDVvZQJWu2RzjvV9W1yNkJNCng2iYQWCxkp7bL"
staker = "MJ6WF1tpEJ7Gk8ULqejDJapRfqBwBEp1dH5QvAgYxu9"

[programs.mainnet]
invariant = "iNvTyprs4TX8m6UeUEkeqDFjAL9zRCRWcexK9Sd4WEU"
staker = "MJ6WF1tpEJ7Gk8ULqejDJapRfqBwBEp1dH5QvAgYxu9"
locker = "LockDkUjGpMHewP4cbP7XRpiiC4ciQaPALbwUALCEJp"
invariant_autoswap = "AuTonVN41Ne17RGR2o9qTj3TmtKcTwmUUy1ebbTmpiU"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000"
